// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJZUjXbV3gy4EVHOjohL5bf0od8Bfe7c',
    appId: '1:587756838414:web:9fa3f2a88af16bbaca265f',
    messagingSenderId: '587756838414',
    projectId: 'supply-on-campus',
    authDomain: 'supply-on-campus.firebaseapp.com',
    storageBucket: 'supply-on-campus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0oRmRZTpOpVLuf2S10SVYLcJbj4Vfi4',
    appId: '1:587756838414:android:cd6126cf9d6c87eeca265f',
    messagingSenderId: '587756838414',
    projectId: 'supply-on-campus',
    storageBucket: 'supply-on-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUo-Fx2IrY-I4ZPUovfAmtuEnbbWODRP0',
    appId: '1:587756838414:ios:a16d0fac8bdbe754ca265f',
    messagingSenderId: '587756838414',
    projectId: 'supply-on-campus',
    storageBucket: 'supply-on-campus.firebasestorage.app',
    iosBundleId: 'com.example.supplyOnCampus',
  );
}
